package com.sentinel_trade.model;

import java.math.BigDecimal;
import java.util.Objects;
import java.util.UUID;

/**
 * Alert event generated by anomaly detection.
 *
 * Requirements: 3.1, 3.2, 3.4
 */
public class Alert {

    public enum AlertType { LARGE_ORDER, FLASH_CRASH }
    public enum Severity  { HIGH, CRITICAL }

    private String alertId;
    private AlertType alertType;
    private String symbol;
    private long timestamp;
    private Severity severity;
    private BigDecimal price;
    private BigDecimal quantity;
    private BigDecimal amount;

    /** Required no-arg constructor for Flink POJO serialization. */
    public Alert() {}

    public Alert(AlertType alertType, String symbol, long timestamp,
                 Severity severity, BigDecimal price, BigDecimal quantity) {
        this.alertId = UUID.randomUUID().toString();
        this.alertType = alertType;
        this.symbol = symbol;
        this.timestamp = timestamp;
        this.severity = severity;
        this.price = price;
        this.quantity = quantity;
        this.amount = price.multiply(quantity);
    }

    // -----------------------------------------------------------------------
    // Getters / Setters
    // -----------------------------------------------------------------------

    public String getAlertId() { return alertId; }
    public void setAlertId(String alertId) { this.alertId = alertId; }

    public AlertType getAlertType() { return alertType; }
    public void setAlertType(AlertType alertType) { this.alertType = alertType; }

    public String getSymbol() { return symbol; }
    public void setSymbol(String symbol) { this.symbol = symbol; }

    public long getTimestamp() { return timestamp; }
    public void setTimestamp(long timestamp) { this.timestamp = timestamp; }

    public Severity getSeverity() { return severity; }
    public void setSeverity(Severity severity) { this.severity = severity; }

    public BigDecimal getPrice() { return price; }
    public void setPrice(BigDecimal price) { this.price = price; }

    public BigDecimal getQuantity() { return quantity; }
    public void setQuantity(BigDecimal quantity) { this.quantity = quantity; }

    public BigDecimal getAmount() { return amount; }
    public void setAmount(BigDecimal amount) { this.amount = amount; }

    // -----------------------------------------------------------------------
    // equals / hashCode / toString
    // -----------------------------------------------------------------------

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Alert)) return false;
        Alert that = (Alert) o;
        return Objects.equals(alertId, that.alertId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(alertId);
    }

    @Override
    public String toString() {
        return "Alert{alertId='" + alertId + "', alertType=" + alertType
                + ", symbol='" + symbol + "', timestamp=" + timestamp
                + ", severity=" + severity + ", amount=" + amount + '}';
    }
}
